version: '3.8'

services:
  data-ingestion:
    build: 
      context: ./services/data-ingestion
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres
      - kafka

  data-processing:
    build: 
      context: ./services/data-processing
      dockerfile: Dockerfile
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master

  calibration-service:
    build: 
      context: ./services/calibration-service
      dockerfile: Dockerfile
    environment:
      - MODEL_PATH=/models
    volumes:
      - ./models:/models

  device-monitoring:
    build: 
      context: ./services/device-monitoring
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  dashboard-frontend:
    build: 
      context: ./services/dashboard-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  # Infrastructure services
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: airqo_pipeline
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  spark-master:
    image: bitnami/spark:3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker:
    image: bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master

volumes:
  postgres_data:
  models: